---
- hosts: all
  sudo: true

  vars_files:
    - vars/secrets.yml

  handlers:
    - name: reload apache
      service: name=apache2 state=reloaded
    - name: restart postgresql
      service: name=postgresql state=restarted

  tasks:
    #Sync data
    - include: tasks/synchronize.yml
    # Add repositories
    - name: update apt cache
      apt: update_cache=yes
    # Upload data
    - include: tasks/upload.yml
    # Databases
    - include: tasks/pgsql.yml
    - include: tasks/mysql.yml
    # Servers
    - include: tasks/apache.yml
    - include: tasks/php.yml
    - include: tasks/php_xdebug.yml
    # Devtools
    - include: tasks/devtools.yml
