---
- name: Apache | Install
  apt: name=apache2 state=present

- name: Apache | Enable modules
  apache2_module: state=present name=rewrite
  notify:
    - reload apache

- name: Apache | Clean WWW
  shell: rm -rf /var/www/html/*

- name: Apache | Install default html
  template:
    src=index.php.j2
    dest=/var/www/html/index.php
  notify:
    - reload apache
