---
# Build tools
- name: Build Tools | Install
  apt: name=build-essential state=present

# Repository Tools
- name: Git | Install
  apt: name=git state=present

# PHP - Composer
- name: Composer | Clone
  shell: cp /sources/composer_installer.php /tmp/

- name: Composer | Build
  shell: php composer_installer.php  chdir=/tmp/

- name: Composer | Install
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: Composer | Update
  shell: composer self-update

- name: NodeJS | Decompression
  shell: tar -zxvf /sources/nodejs.tar.gz -C /

- name: NodeJS | Move to tmp
  command: mv /sources/nodejs /tmp/nodejs

- name: NodeJS | Configure
  shell: ./configure  chdir=/tmp/nodejs/

- name: NodeJS | Make
  shell: make  chdir=/tmp/nodejs/

- name: NodeJS | Inatall
  shell: make install  chdir=/tmp/nodejs/

# Language - Ruby
- name: Ruby | Install
  apt: name={{ item }} state=present
  with_items:
    - ruby

# Bower
- name: Bower | Install
  shell: npm install -g bower

#grunt
- name: Grunt | Install
  shell: npm install -g grunt-cli

# Sass compiler
- name: Sass | Install
  shell: gem install sass

# Compass
- name: Compass | install
  shell: npm install compass