---
# Build tools
- name: install build tools
  apt: name=build-essential state=present

# Repository Tools
- name: install git
  apt: name=git state=present

# PHP - Composer
- name: Composer | Clone
  shell: cp /sources/composer_installer.php /tmp/

- name: Composer | Build
  shell: php composer_installer.php  chdir=/tmp/

- name: Composer | Install
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: Composer | Update
  shell: composer self-update

# Language - Nodejs
#- name: NodeJS | Clone
  #shell: git clone https://github.com/joyent/node.git
  #shell: cd node
  #shell: git checkout v0.12.0
  #git: repo=https://github.com/joyent/node.git
  #       dest=/tmp/node
  #       version={{node_version}}
  #shell: cp /sources/nodejs /tmp/nodejs/ -R

- name: NodeJS | Decompression
  shell: tar -zxvf /sources/nodejs.tar.gz -C /

- name: NodeJS | Move to tmp
  command: mv /sources/nodejs /tmp/nodejs

- name: NodeJS | Configure
  shell: ./configure  chdir=/tmp/nodejs/

- name: NodeJS | Make
  shell: make  chdir=/tmp/nodejs/

- name: NodeJS | Inatall
  shell: make install  chdir=/tmp/nodejs/

# Language - Ruby
- name: install ruby-full
  apt: name={{ item }} state=present
  with_items:
    - ruby

# Bower
- name: install bower
  shell: npm install -g bower

# Sass compiler
- name: install sass
  shell: gem install sass

# Compass
- name: install compass
  shell: npm install compass