---
- name: MySQL | Install
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
    - mysql-server
    - libmysqlclient18

- name: MySQL | Create user
  mysql_user: name="{{mysql_username}}" password="{{mysql_password}}" priv=*.*:ALL state=present


