---
- name: install mysql
  apt: name={{ item }} state=present
  with_items:
    - mysql-common
    - libmysqlclient18
    - python-mysqldb

- name: create mysql user
  mysql_user: name="{{mysql_username}}" password="{{mysql_password}}" priv=*.*:ALL state=present


