---
- name: install postgresql
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - python-psycopg2
    - postgresql

#- name: Make sure its running
#  service: name=postgresql state=started enabled=yes

- name: start postgresql
  service: name=postgresql state=started

- lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf
              regexp='local\s+all\s+postgres\s+peer'
              line='local all postgres trust'
              insertbefore=BOF
  notify: restart postgresql

- name: restart postgresql
  service: name=postgresql state=restarted

- name: create pgsql user
  sudo: yes
  postgresql_user: name="{{ pgsql_username }}"  password="{{pgsql_password}}" role_attr_flags=NOSUPERUSER,CREATEDB
  notify: restart postgresql
