---
- name: PostgreSQL | Install libraries
  apt: name={{ item }} state=present
  with_items:
    # build
    - build-essential
    - libreadline-dev
    - zlib1g-dev
    - flex
    - bison
    - libxml2-dev
    - libxslt-dev
    - libssl-dev
    - make
    # ansible remote control modules
    - libpq-dev
    - python-psycopg2

- name: PostgreSQL | Decompression
  shell: tar -zxvf /sources/postgres.tar.gz -C /

- name: PostgreSQL | Move to tmp
  command: mv /sources/postgres /tmp/postgres

- name: PostgreSQL | Configure
  shell: ./configure  chdir=/tmp/postgres/

- name: PostgreSQL | Make
  shell: make  chdir=/tmp/postgres/

- name: PostgreSQL | Inatall
  shell: make install  chdir=/tmp/postgres/

- name: PostgreSQL | Add system service
  shell: cp /tmp/postgres/contrib/start-scripts/linux /etc/init.d/postgres

- name: PostgreSQL | Make service executable
  shell: chmod +x  /etc/init.d/postgres

- name: PostgreSQL | Add paths
  template:
    src=etc/profile.d/postgres.sh
    dest=/etc/profile.d/postgres.sh
  notify:
    - reload apache

- name: PostgreSQL | Load paths
  shell: bash /etc/profile.d/postgres.sh

- name: PostgreSQL | Create postgres user
  user: name=postgres

- name: PostgreSQL | Create data directory
  shell: mkdir /usr/local/pgsql/data -p

- name: PostgreSQL | Set owner of data directory
  shell: chown postgres:postgres /usr/local/pgsql/data

- name: PostgreSQL | Initialize data directory
  shell: /usr/local/pgsql/bin/initdb -D /usr/local/pgsql/data/
  sudo: yes
  sudo_user: postgres

- name: PostgreSQL | Start service
  shell: service postgres start

- name: PostgreSQL | Start service on boot
  shell: sudo update-rc.d postgres defaults

- name: PostgreSQL | Create user
  shell: /usr/local/pgsql/bin/psql -c "CREATE ROLE {{pgsql_username}} LOGIN PASSWORD '{{pgsql_password}}' SUPERUSER CREATEDB CREATEROLE;"
  sudo: yes
  sudo_user: postgres
