---
- name: install php
  apt: name=php5-curl state=present

- name: Enable curl
  file:
    src=/etc/apache2/sites-available/vagrant.conf
    dest=/etc/apache2/sites-enabled/vagrant.conf
    state=link
  notify:
    - reload apache