---
- name: Synchronize | Install
  apt: name={{ item }} state=present
  with_items:
    - rsync

# Synchronize local and files files
#- name: Synchronize | Global WWW directory
#  synchronize: src=files/var/www/ dest=/var/www/ rsync_path="sudo rsync"

#- name: Synchronize | Apache config
#  synchronize: src=files/etc/apache2/sites-enabled/ dest=/etc/apache2/sites-enabled/ rsync_path="sudo rsync"
